# Generated by Django 2.1.3 on 2019-01-15 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('occupation', models.CharField(max_length=255, null=True)),
                ('profile_pic', models.ImageField(null=True, upload_to='images/')),
                ('username', models.EmailField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('date_of_birth', models.DateField(default='2000-01-01')),
                ('mobile', models.CharField(default=0, max_length=11)),
                ('address', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Financer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('profile_pic', models.ImageField(upload_to='images/')),
                ('username', models.EmailField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('date_of_birth', models.DateField(default='2000-01-01')),
                ('mobile', models.CharField(default=0, max_length=11)),
                ('address', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('account_balance', models.BigIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='consumer',
            name='financer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Financer'),
        ),
    ]
